test: remove channel in rule 901 end to end test
frmscoe/postman pull request #55
Opened 2024-05-22 13:35 UTC by Sandy-at-Tazama

Removed channel from rule 901 end to end test

2024-05-22 18:45 UTC, Justus-at-Tazama requested changes
I think you forgot a console log, but not sure.

2024-05-22 18:45 UTC, Justus-at-Tazama commented on 1.1. Rule-901 End-to-End test - pain001-013 disabled.postman_collection.json
> +									"\r",
Did you forget to remove this again, or did you leave it in intentionally?

2024-05-22 19:37 UTC, Sandy-at-Tazama commented
Forgot. Sorry
S

On Wed, 22 May 2024, 20:45 Justus Ortlepp, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> I think you forgot a console log, but not sure.
> ------------------------------
>
> In 1.1. Rule-901 End-to-End test - pain001-013
> disabled.postman_collection.json
> <https://github.com/frmscoe/postman/pull/55#discussion_r1610483083>:
>
> > @@ -613,6 +613,9 @@
>  							"script": {
>  								"exec": [
>  									"const resJson = pm.response.json();\r",
> +									"\r",
> +									"console.log(resJson);\r",
> +									"\r",
>
> Did you forget to remove this again, or did you leave it in intentionally?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/frmscoe/postman/pull/55#pullrequestreview-2072090851>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BB55QAZQD3IO52M4TWZR7C3ZDTRVPAVCNFSM6AAAAABIDVOJ62VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANZSGA4TAOBVGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-23 07:50 UTC, Justus-at-Tazama approved these changes

2024-05-23 07:50 UTC, merged