feat: Updating the collections for the v2.0.0 changes.
frmscoe/postman pull request #80
Opened 2024-07-26 12:53 UTC by vorsterk

# SPDX-License-Identifier: Apache-2.0

## What did we change?

## Why are we doing this?

## How was it tested?
- [x] Locally
- [x] Development Environment
- [ ] Not needed, changes very basic
- [ ] Husky successfully run
- [ ] Unit tests passing and Documentation done

2024-07-26 12:59 UTC, Justus-at-Tazama requested changes
Please use environment variables from the Postman environment variable file instead of hard-coded database and collection names.

2024-07-26 12:59 UTC, Justus-at-Tazama commented on ArangoDB Setup.json
> +							"raw": "{{arangoUrl}}/_db/configuration/_api/collection",
These strings exist in the environment files as environment variables, e.g. `{{db_config_all}}` for `configuration` - these values have been updated in the `tms-configuration` collections as well, for reference. Can we please update these hard-coded database and collection names to use the environment variables?

2024-07-29 10:55 UTC, TARIQ-BARKI commented
there is an error in the execution of the file :
1.  TypeError                             Cannot read properties of undefined (reading 'report')
                                           at test-script
                                           inside "DB update tests / Fetch evaluation results with msgId - Rule 901 Network Map Only"

2024-07-29 14:20 UTC, Justus-at-Tazama approved these changes

2024-07-29 14:30 UTC, merged